// <auto-generated />
using ExampleDbContext;
using ExampleDbContext.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Microsoft.EntityFrameworkCore.ValueGeneration;
using System;

namespace ExampleDbContext.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20180308180351_People")]
    partial class People
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ExampleDbContext.Entities.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("BirthDate");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<int>("Gender");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("People");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Person");
                });

            modelBuilder.Entity("ExampleDbContext.Entities.Customer", b =>
                {
                    b.HasBaseType("ExampleDbContext.Entities.Person");


                    b.ToTable("Customer");

                    b.HasDiscriminator().HasValue("Customer");
                });

            modelBuilder.Entity("ExampleDbContext.Entities.Director", b =>
                {
                    b.HasBaseType("ExampleDbContext.Entities.Person");


                    b.ToTable("Director");

                    b.HasDiscriminator().HasValue("Director");
                });

            modelBuilder.Entity("ExampleDbContext.Entities.Employer", b =>
                {
                    b.HasBaseType("ExampleDbContext.Entities.Person");


                    b.ToTable("Employer");

                    b.HasDiscriminator().HasValue("Employer");
                });

            modelBuilder.Entity("ExampleDbContext.Entities.Manager", b =>
                {
                    b.HasBaseType("ExampleDbContext.Entities.Person");


                    b.ToTable("Manager");

                    b.HasDiscriminator().HasValue("Manager");
                });
#pragma warning restore 612, 618
        }
    }
}
